app:
  string: "a-string"
  data-size: "1MB"
  string-list: [ "string-1", "string-2" ]
  nested-list:
    - a-int: 1
    - a-int: 2
  string-map:
    a: alpha
    b: bravo
  nested-map:
    a:
      a-int: 5
    b:
      a-int: 6
  nested:
    a-int: 3
  nested-not-inner:
    a-int: 4

app.ctor:
  string: "a-string"
  data-size: "1MB"
  string-list: [ "string-1", "string-2" ]
  nested-list:
    - a-int: 1
    - a-int: 2
  nested:
    a-int: 3
  nested-not-inner:
    a-int: 4

app.record:
  string: "a-string"
  data-size: "1MB"
  string-list: [ "string-1", "string-2" ]
  nested-list:
    - a-int: 1
    - a-int: 2
  nested:
    a-int: 3
  nested-not-inner:
    a-int: 4

spring:
  config:
    import: test.yaml
  main:
    banner-mode: off
